### ISSUE TITLE
Upgrade cannot be resumed

### ISSUE THREAD

**Issue by mhutter** [projectsyn/boatswain#39]
When an upgrade is aborted, restarting it will lead to a panic.

## Steps to Reproduce the Problem

  1. Start the "upgrade" task
  1. abot process (`^C`)
  1. restart "upgrade"

```
Ignoring ASG without launch template
ASG cust-test1-builders-120200310100733520700000017 0/6 instances, latest LT version 14
ASG cust-test1-workers-120200319135047187100000005 3/6 instances, latest LT version 13
Instance i-0123456789abcdef (ip-10-200-xxx-xxx.eu-central-1.compute.internal) uses old LaunchTemplateVersion 12
Cordon node
Cordoning node ip-10-200-xxx-xxx.eu-central-1.compute.internal
Replace ASG instance i-oldinstanceid
Detaching node
5015d1a5-0a70-032e-6a69-504106ff268a
Waiting for scale-up
[0] Detaching activity status: InProgress ()
New instance not created yet
^C
```

## Actual Behavior

```
Ignoring ASG without launch template
ASG cust-test1-builders-120200310100733520700000017 0/6 instances, latest LT version 14
ASG cust-test1-workers-120200319135047187100000005 3/6 instances, latest LT version 13
Instance i-oldinstanceid (ip-10-200-xxx-xxx.eu-central-1.compute.internal) uses old LaunchTemplateVersion 12
Cordon node
Cordoning node ip-10-200-xxx-xxx.eu-central-1.compute.internal
Replace ASG instance i-oldinstanceid
Detaching node
panic: ValidationError: The instance i-oldinstanceid is not in InService or Standby.
        status code: 400, request id: cb485354-015f-4e7b-9c8e-59bfdcdec104 [recovered]
        panic: ValidationError: The instance i-oldinstanceid is not in InService or Standby.
        status code: 400, request id: cb485354-015f-4e7b-9c8e-59bfdcdec104

goroutine 1 [running]:
github.com/alecthomas/kong.catch(0xc00073fee8)
        /go/pkg/mod/github.com/alecthomas/kong@v0.2.11/kong.go:366 +0xb3
panic(0x1a19c40, 0xc0004fcc50)
        /usr/local/go/src/runtime/panic.go:969 +0x175
github.com/projectsyn/boatswain/cmd/boatswain.(*Boatswain).Upgrade(0xc000022440, 0x0, 0x0, 0x0, 0x10, 0xc00042e1e0)
        /src/boatswain/cmd/boatswain/upgrade.go:48 +0x77f
main.(*UpgradeCmd).Run(0xc00006a8d8, 0xc00006a980, 0x0, 0x0)
        /src/boatswain/commands.go:57 +0x65
reflect.Value.call(0x1b02540, 0xc00006a8d8, 0x213, 0x1df46da, 0x4, 0xc00042e180, 0x1, 0x1, 0x1, 0x0, ...)
        /usr/local/go/src/reflect/value.go:475 +0x8c7
reflect.Value.Call(0x1b02540, 0xc00006a8d8, 0x213, 0xc00042e180, 0x1, 0x1, 0x0, 0x1, 0xc0001bfe58)
        /usr/local/go/src/reflect/value.go:336 +0xb9
github.com/alecthomas/kong.callMethod(0x1df4256, 0x3, 0x1c2ca40, 0xc00006a8d8, 0x199, 0x1b02540, 0xc00006a8d8, 0x213, 0xc000326f90, 0x2, ...)
        /go/pkg/mod/github.com/alecthomas/kong@v0.2.11/callbacks.go:71 +0x4b1
github.com/alecthomas/kong.(*Context).RunNode(0xc00006a980, 0xc000444410, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/alecthomas/kong@v0.2.11/context.go:610 +0x571
github.com/alecthomas/kong.(*Context).Run(0xc00006a980, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/alecthomas/kong@v0.2.11/context.go:627 +0x99
main.main()
        /src/boatswain/main.go:74 +0x1b0
make: *** [upgrade] Error 2
```

## Expected Behavior

Upgrade is continued from where it was aborted

**Comment by simu** [comment]
Fixing this will need some logic to ignore still-running instances that are already detached from the auto-scaling group.

Additionally it's unclear to me right now how we'll detect that a previously triggered scale-up has finished after boatswain was aborted and restarted, since the ASG activity API is not that great. Having this detection is important in order to avoid draining the old instance before the replacement instance is ready.

**Comment by mhutter** [comment]
Some ideas: Tagging detached instances with the instance ID they are being replaced with, or the other way around

**Comment by simu** [comment]
Closing since we're not maintaining boatswain any longer
