### ISSUE TITLE
panic: the server is currently unable to handle the request (get pods)

### ISSUE THREAD

**Issue by megian** [projectsyn/boatswain#67]
Happened once during a regular maintenance. Creating the issue for documentation purposes.

```
1 pods pending, sleeping
node-shell-c294aeeb-c3ef-45db-ac18-70b15f2a5871
1 pods pending, sleeping
node-shell-c294aeeb-c3ef-45db-ac18-70b15f2a5871
1 pods pending, sleeping
panic: the server is currently unable to handle the request (get pods) [recovered]
    panic: the server is currently unable to handle the request (get pods)
 
goroutine 1 [running]:
github.com/alecthomas/kong.catch(0xc001005ee8)
    /go/pkg/mod/github.com/alecthomas/kong@v0.2.12/kong.go:365 +0xb3
panic(0x1a899e0, 0xc000d6dc80)
    /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/projectsyn/boatswain/cmd/boatswain.(*Boatswain).Upgrade(0xc0006b8a80, 0x0, 0x0, 0x0, 0x10, 0xc00069f220)
    /src/boatswain/cmd/boatswain/upgrade.go:48 +0x77f
main.(*UpgradeCmd).Run(0xc0001549d8, 0xc000154a80, 0x0, 0x0)
    /src/boatswain/commands.go:57 +0x65
reflect.Value.call(0x1b7ba20, 0xc0001549d8, 0x213, 0x1e7ffba, 0x4, 0xc00069f200, 0x1, 0x1, 0x1, 0x0, ...)
    /usr/local/go/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0x1b7ba20, 0xc0001549d8, 0x213, 0xc00069f200, 0x1, 0x1, 0x0, 0x1, 0xc0005a3f18)
    /usr/local/go/src/reflect/value.go:337 +0xb9
github.com/alecthomas/kong.callMethod(0x1e7fb50, 0x3, 0x1cac780, 0xc0001549d8, 0x199, 0x1b7ba20, 0xc0001549d8, 0x213, 0xc0002973e0, 0x0, ...)
    /go/pkg/mod/github.com/alecthomas/kong@v0.2.12/callbacks.go:71 +0x4b1
github.com/alecthomas/kong.(*Context).RunNode(0xc000154a80, 0xc0006a4dd0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/alecthomas/kong@v0.2.12/context.go:679 +0x571
github.com/alecthomas/kong.(*Context).Run(0xc000154a80, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/alecthomas/kong@v0.2.12/context.go:696 +0x99
main.main()
    /src/boatswain/main.go:74 +0x1b0
    ```

## Steps to Reproduce the Problem

Unknown, didn't happen after the second try.

## Actual Behavior
Seems to happen irregular.

## Expected Behavior
Workaround is to restart boatswain, therefore we might life with the issue.

**Comment by megian** [comment]
Didn't occur anymore.
